# Let's see some basic usages of Numpy
### First of all import numpy

In [1]:
import numpy as np

# let's do some basic stuff

In [2]:
# Create an array with just one specific element
array_one = np.array(5)
array_one

array(5)

In [3]:
# Use a range of numbers for creating your array
# This creates any array using 0 to 14 ascending
array_two = np.arange(15)
array_two

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Use np.reshape() to reshape the array directly
# You cannot reshape the array to irrational ratio like 3 times 4 , according to your original array
# array_two to has 1 row  times 15 columns
# This will make array_two 3 times 5
# np.reshape(row,column)
array_three = array_two.reshape(3,5)
array_three

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# See what the shape of array is
# it's an 15-element array
array_two.shape

(15,)

In [6]:
array_three.shape
# It says that yout array includes 3 rows and 5 columns

(3, 5)

In [7]:
# See the number of dimentions
array_three.ndim

2

In [8]:
# How many elements does it has
array_three.size

15

In [9]:
# See the type of the array
array_three.dtype

dtype('int64')

In [10]:
array_four = np.arange(20)
array_four

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
# reshape the array to a 3D matrix
array_five = array_four.reshape(2,5,2)
print(array_five)
print('This is the shape of array : ',array_five.shape)
print('This is the dimention of array : ',array_five.ndim)
print('This is the size of array : ',array_five.size)
print('This is the type of array : ',array_five.dtype)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
This is the shape of array :  (2, 5, 2)
This is the dimention of array :  3
This is the size of array :  20
This is the type of array :  int64


In [12]:
# produce data
# create an array of zeros or ones
# (rows,colums)
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
one_array = np.ones((3,4))
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Some operations on arrays

In [14]:
array_six = np.array([20,30,40,50])
array_seven = np.arange(4)

In [15]:
array_six - array_seven

array([20, 29, 38, 47])

In [16]:
array_six + array_seven

array([20, 31, 42, 53])

In [17]:
# normal multiply
array_eight = array_six * array_seven

In [18]:
array_eight > 50

array([False, False,  True,  True])

In [19]:
np.sin(array_eight)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])